### ISSUE TITLE
Unable to install Batch or Bash Editors

### ISSUE THREAD

**Issue by buddybu** [de-jcup/eclipse-batch-editor#14]
When attempting installation, I get the following error:

> Unable to read repository at https://dl.bintray.com/de-jcup/batcheditor/content.xml.
> Unable to read repository at https://dl.bintray.com/de-jcup/batcheditor/content.xml.
> sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

When I visit the site, https://dl.bintray.com/de-cup/batcheditor, there is no content.xml file located there.  Same for bash editor

**Comment by buddybu** [comment]
This looks to be blocked by my corporate firewall.  Closing.

**Comment by de-jcup** [comment]
Hello @buddybu , if you have still problems with installation, please look into
https://github.com/de-jcup/eclipse-bash-editor/issues/110

There I described the way to install bash-editor from a local update site.
Because of missing https://dl.bintray.com/de-jcup/batcheditor/content.xml : This is normal, because 
https://dl.bintray.com/de-jcup/batcheditor/content.jar is the preferred way and contains same as xml (but zipped). The xml file will only tried to be loaded when jar not found (e.g. when blocked by a firewall, or as it seems like in your stacktrace the certificates from bintray are not accepted)

Hope this info helps.
